name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java-version: [17]

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1


      - name: Configure JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}

      - name: Build Process Watcher
        uses: cdsap/build-process-watcher@v0.6.2
        with:
          remote_monitoring: 'true'
          export_to_bigquery: 'true'

      - name: Run Tests
        run: ./gradlew test
